name: bpbd_presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  shared_preferences: ^2.1.0
  file_picker: ^5.2.9
  shimmer: ^2.0.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.0+1
  geolocator: ^9.0.2
  image_picker: ^1.0.7
  flutter_image_compress: ^2.2.0
  permission_handler: ^10.2.0
  intl: ^0.18.0
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
